apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local   
    app: db
  name: {{ .Values.pvName }}
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  