apiVersion: v1
kind: Service
metadata:
  labels:
    app: fastapi
  name: fastapi
  namespace: default
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 5000
  selector:
    app: fastapi
status:
  loadBalancer: {}
