apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: postgres-data
  name: postgres-pv-volume
spec:
  storageClassName: "gp2"
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  