apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.dbName }}
  name: {{ .Values.dbName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "portpostgresql"
      port: 5432
      targetPort: 5432
  selector:
    app: {{ .Values.dbName }}


