apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.fastapiName }}
  name: {{ .Values.service.name}}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.fastapiName }}
  type: {{ .Values.service.type }}