apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.fastapiName }}
  name: {{ .Values.fastapiName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.fastapiName }}
