apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.pgName }}
  name: {{ .Values.pgName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.pgName }}
  template:
    metadata:
      labels:
        app: {{ .Values.pgName }}
    spec:
      containers:
        - env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@admin.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: root
          image: "{{ .Values.image.repositrory_pg }}"
          name: {{ .Values.pgName }}
          ports:
            - containerPort: 80
              hostPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always