apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.pgName }}
  name: {{ .Values.pgName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
  selector:
    app: {{ .Values.pgName }}
