apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  serviceName: db
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:   
      containers:
        - name: postgres
          image: postgres:12.0-alpine
          imagePullPolicy: "IfNotPresent"  
          ports:
            - containerPort: 5432        
          env:
            - name: POSTGRES_DB
              value: storedb
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-fastapi-userpass
                  key: password
            - name: POSTGRES_USER
              value: admin
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-db
      volumes:
          - name: postgres-db
            persistentVolumeClaim:
              claimName: {{ .Values.pvcName }}
          



  # volumeClaimTemplates:
  #   - metadata:
  #       name: postgres-db
  #     spec:
  #       accessModes: [ "ReadWriteOnce" ]
  #       storageClassName: manual
  #       resources:
  #         requests:
  #           storage: 100Mi

      