apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.fastapiName }}
  name: {{ .Values.fastapiName }}
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: {{ .Values.fastapiName }}
  type: NodePort

