apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.fastapiName }}
  name: {{ .Values.fastapiName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    app: {{ .Values.fastapiName }}
status:
  loadBalancer: {}
