apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: postgres-data
  name: postgres-pv-volume
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: "gp2"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  