apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres-data
  name: postgres-pv-claim
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: db-gp2
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 100Mi

