apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local   
    app: db
  name: postgres-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  