apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-pgadmin 
  namespace: dev 
  generation: 2 
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /
    #kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Script-Name /pgadmin;
spec:
  ingressClassName: nginx
  rules:
  - host: public.my-services.com 
    http:
      paths:
      - path: /pgadmin
        pathType: ImplementationSpecific
        backend:
          service:
            name: pgadmin-dev
            port:
              number: 8080
