apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-pgadmin 
  namespace: dev  
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: fastapi.service.com
    http:
      paths:
      - path: /pgadm
        pathType: Prefix
        backend:
          service:
            name: pgadmin-dev
            port:
              number: 8080
